apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-app-operator-system

namePrefix: simple-app-operator-

resources:
  - crd.yaml
  - rbac.yaml
  - manager.yaml

images:
  - name: controller
    newTag: "latest"
